Высылаю резюме.
BankEx/bankex_foundation_education pull request #2
Opened 2017-12-14 20:07 UTC by Rovenich

Ровенский А.В.

2017-12-15 08:33 UTC, skywinder commented on README.md
> -This repository is made to accept solutions of tasks for students.
Отлично! Ты первый, тебе плюс в карму ;)
Все хорошо, только не удаляй корневой ридми пожалуйста. Нужно ее вернуть обратно в еще один одном комиье при помощи команды revert например. Справишься?

2017-12-15 08:35 UTC, skywinder requested changes

2017-12-15 08:35 UTC, skywinder commented on Ровенский/Резюме.md
> +Являлся разработкчиком интерактивного информационного стенда. Участвовал во многих научных мероприятиях таких как: «Шаг в будущем», «Научная ярмарка и бизнес-идей», XXIII Региональных Научных сообщес
Напиши, какие языки и фреймворки использовал 👍

2017-12-16 19:59 UTC, Rovenich commented on Ровенский/Резюме.md
> +Являлся разработкчиком интерактивного информационного стенда. Участвовал во многих научных мероприятиях таких как: «Шаг в будущем», «Научная ярмарка и бизнес-идей», XXIII Региональных Научных сообщес
хорошо

2017-12-17 00:03 UTC, skywinder requested changes

2017-12-17 00:03 UTC, skywinder commented on README.md
> +# bankex_foundation_education
изменения в основной ридми вообще не нужно вносить. ты можешь отменить его, нажав revert например

2017-12-17 00:03 UTC, skywinder commented on Ровенский/Резюме.md
> +<<<<<<< HEAD
это правки от merge conflict. стрелочки нужно удалить

2017-12-17 00:03 UTC, skywinder commented on Ровенский/Резюме.md
> +=======
и тут. и все что между этими стрелочками-  у тебя дубликат получился

2017-12-17 00:03 UTC, skywinder commented on Ровенский/Резюме.md
> +>>>>>>> 503b1926b29f882ebc779b3fe3d291b16f0ef44b
таже история

2017-12-18 17:15 UTC, merged