-
BankEx/bankex_foundation_education pull request #29
Opened 2017-12-21 07:47 UTC by andrejnekrasov

2017-12-22 22:26 UTC, skywinder requested changes

2017-12-22 22:26 UTC, skywinder commented on Nekrasov Andrei/Nekrasov Andrei - Resume
> +Некрасов Андрей
Все хорошо, только файл лучше назвать с постфиксом .md - что бы формат был понятен

2017-12-22 22:26 UTC, skywinder commented on Nekrasov Andrei/wallet.md
> +https://etherscan.io/address/0x8ae8e8a20038e1dfc23803b7200929e40f2c0e52
все верно, только тут адрес без префикса rinkeby - поэтому ссылка на боевой эфир и там пусто по ней.

2018-02-06 22:43 UTC, artall64 commented
Закрываю т.к. нет активности

2018-02-06 22:43 UTC, closed without merging