Task 1
BankEx/bankex_foundation_education pull request #57
Opened 2018-02-06 19:56 UTC by wadmilionikus

2018-02-06 21:54 UTC, artall64 requested changes

2018-02-06 21:54 UTC, artall64 commented on wadmilionikus/Task1/Readme.md
> +Created token: https://rinkeby.etherscan.io/tx/0x25d4bf58afa0b8970e770d4188efeadba94277f1e7d1527f5f57571ce32fb40d
Можете добавит сслыку на контракта в etherscan

2018-02-08 10:01 UTC, wadmilionikus commented on wadmilionikus/Task1/Readme.md
> +Created token: https://rinkeby.etherscan.io/tx/0x25d4bf58afa0b8970e770d4188efeadba94277f1e7d1527f5f57571ce32fb40d
добавил

2018-02-11 13:41 UTC, wadmilionikus reviewed
добавил

2018-02-11 21:35 UTC, artall64 commented on wadmilionikus/Task1/Readme.md
> +Created token: https://rinkeby.etherscan.io/token/0xdfd4a0829b75f957cf6c18a80ded18fb57c1e9c8?a=0x6203f62ce77d58e0e85bef5af457befe6ae65c30
Я имел ввиду добавить эту ссылку:
https://rinkeby.etherscan.io/address/0xdfd4a0829b75f957cf6c18a80ded18fb57c1e9c8#code
Можешь также выложить исходный код контракта в Etherscan: MISC -> Verify Contract

2018-02-25 14:32 UTC, closed without merging

2018-02-25 14:33 UTC, artall64 commented
Исходный код контракта не выложе в Etherscan.
Как только будет добавлен, новый pull request будет принят